--------------------------------------------------------
--  File created - Tuesday-March-31-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EVENTOAUDITORIA
--------------------------------------------------------

  CREATE TABLE "AUDITORIAS"."EVENTOAUDITORIA" 
   (	"IDEVENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TIPOEVENTO" VARCHAR2(100 BYTE), 
	"USUARIOINVOLUCRADO" VARCHAR2(150 BYTE), 
	"HORARIOEVENTO" TIMESTAMP (6), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "AUDITORIAS"."USUARIOS" 
   (	"IDUSUARIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(150 BYTE), 
	"ROL" VARCHAR2(20 BYTE), 
	"ACTIVO" NUMBER DEFAULT 1, 
	"FECHAREGISTRO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AUDITORIAS.EVENTOAUDITORIA
SET DEFINE OFF;
Insert into AUDITORIAS.EVENTOAUDITORIA (IDEVENTO,TIPOEVENTO,USUARIOINVOLUCRADO,HORARIOEVENTO,DESCRIPCION) values (4,'CREAR_USUARIO','noe@sistema.com',to_timestamp('26-MAR-26 03.52.23.782781000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Se creo el usuario:Noe Martienz | Rol: USER');
Insert into AUDITORIAS.EVENTOAUDITORIA (IDEVENTO,TIPOEVENTO,USUARIOINVOLUCRADO,HORARIOEVENTO,DESCRIPCION) values (5,'ACTUALIZAR_USUARIO','jorge@sistema.com',to_timestamp('26-MAR-26 03.54.29.585631000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Se actualizo el usuario: Jorge Aguilar | Nuevo rol: ADMIN');
Insert into AUDITORIAS.EVENTOAUDITORIA (IDEVENTO,TIPOEVENTO,USUARIOINVOLUCRADO,HORARIOEVENTO,DESCRIPCION) values (6,'DESACTIVAR_USUARIO','jorge@sistema.com',to_timestamp('26-MAR-26 03.55.08.579896000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Se desactivo el usuario: Jorge Aguilar');
Insert into AUDITORIAS.EVENTOAUDITORIA (IDEVENTO,TIPOEVENTO,USUARIOINVOLUCRADO,HORARIOEVENTO,DESCRIPCION) values (1,'CREAR_USUARIO','ana@sistema.com',to_timestamp('24-MAR-26 12.31.38.293625000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Se creo el usuario:Ana Torres | Rol: USER');
Insert into AUDITORIAS.EVENTOAUDITORIA (IDEVENTO,TIPOEVENTO,USUARIOINVOLUCRADO,HORARIOEVENTO,DESCRIPCION) values (2,'ACTUALIZAR_USUARIO','ana.nueva@sistema.com',to_timestamp('24-MAR-26 01.03.01.526083000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Se actualizo el usuario: Ana Torres Actualizada | Nuevo rol: ADMIN');
Insert into AUDITORIAS.EVENTOAUDITORIA (IDEVENTO,TIPOEVENTO,USUARIOINVOLUCRADO,HORARIOEVENTO,DESCRIPCION) values (3,'DESACTIVAR_USUARIO','user@sistema.com',to_timestamp('24-MAR-26 01.04.20.351523000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Se desactivo el usuario: Usuario Normal');
REM INSERTING into AUDITORIAS.USUARIOS
SET DEFINE OFF;
Insert into AUDITORIAS.USUARIOS (IDUSUARIO,NOMBRE,CORREO,ROL,ACTIVO,FECHAREGISTRO) values (1,'Administrador','admin@sistema.com','ADMIN',1,to_timestamp('24-MAR-26 11.51.29.651000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into AUDITORIAS.USUARIOS (IDUSUARIO,NOMBRE,CORREO,ROL,ACTIVO,FECHAREGISTRO) values (2,'Usuario Normal','user@sistema.com','USER',0,to_timestamp('24-MAR-26 11.51.29.701000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into AUDITORIAS.USUARIOS (IDUSUARIO,NOMBRE,CORREO,ROL,ACTIVO,FECHAREGISTRO) values (3,'Carlos Mendez','carlos@sistema.com','USER',1,to_timestamp('24-MAR-26 11.51.29.713000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into AUDITORIAS.USUARIOS (IDUSUARIO,NOMBRE,CORREO,ROL,ACTIVO,FECHAREGISTRO) values (4,'Laura Gomez','laura@sistema.com','USER',1,to_timestamp('24-MAR-26 11.51.29.721000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into AUDITORIAS.USUARIOS (IDUSUARIO,NOMBRE,CORREO,ROL,ACTIVO,FECHAREGISTRO) values (6,'Jorge Aguilar','jorge@sistema.com','ADMIN',0,to_timestamp('26-MAR-26 03.52.23.342361000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into AUDITORIAS.USUARIOS (IDUSUARIO,NOMBRE,CORREO,ROL,ACTIVO,FECHAREGISTRO) values (5,'Ana Torres Actualizada','ana.nueva@sistema.com','ADMIN',1,to_timestamp('24-MAR-26 12.31.29.249415000 PM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  Constraints for Table EVENTOAUDITORIA
--------------------------------------------------------

  ALTER TABLE "AUDITORIAS"."EVENTOAUDITORIA" MODIFY ("IDEVENTO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."EVENTOAUDITORIA" MODIFY ("TIPOEVENTO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."EVENTOAUDITORIA" MODIFY ("HORARIOEVENTO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."EVENTOAUDITORIA" ADD PRIMARY KEY ("IDEVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "AUDITORIAS"."USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."USUARIOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."USUARIOS" MODIFY ("ROL" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."USUARIOS" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."USUARIOS" MODIFY ("FECHAREGISTRO" NOT NULL ENABLE);
  ALTER TABLE "AUDITORIAS"."USUARIOS" ADD PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUDITORIAS"."USUARIOS" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
